version: "3.3"

services:
  vue:
    working_dir: /home/vue
    build: .
    volumes:
      - ./:/home/vue
    ports:
      - 8000:8000 # vue ui
      - 8080:8080 # vue dev
      - 6006:6006 # storybook
